apiVersion: extensions/v1beta1
kind: Ingress
metadata: 
  name: vocbench-ingress-tls
  namespace: vocbench
  annotations: 
    kubernetes.io/ingress.class: nginx
    cert-manager.io/cluster-issuer: letsencrypt-staging
spec: 
  rules:
  - host: vocbench-dev.officialstatistics.org
    http:
      paths:
      - path: /*
        backend:
          serviceName: vocbench3
          servicePort: 80
  tls:
  - hosts:
    - vocbench-dev.officialstatistics.org
    secretName: echo-tls