apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: voc

resources:
  - graphdb.statefulset.yaml
  - index.configmap.yaml
  - nginx.configmap.yaml
  - vocbench.statefulset.yaml
  - ingress.yaml